spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: luochat
  datasource:
    url: jdbc:mysql://${luochat.mysql.ip}:${luochat.mysql.port}/${luochat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${luochat.mysql.username}
    password: ${luochat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${luochat.redis.host}
    # Redis服务器端口号
    port: ${luochat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${luochat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true